In [8]:
import numpy as np
import pandas as pd

In [2]:
a1 = np.array([[1,2,3,4]])

In [3]:
a1.ndim

2

In [10]:
df= pd.Series([1,2,3,4])
df

0    1
1    2
2    3
3    4
dtype: int64

In [17]:
df[2]

np.int64(3)

In [12]:
a2 = a1.flatten() # convert high dim to one dim

In [15]:
a3 = pd.Series(a2) # convert numpy array to pandas Series.
a3

0    1
1    2
2    3
3    4
dtype: int64

# data frame

In [22]:
df = pd.DataFrame([[1,2,3,4],[5,6,7,8]])

In [23]:
df

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

  # treating missing value

In [26]:
import seaborn as sns

In [28]:
df = sns.load_dataset("titanic")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [29]:
df.shape

(891, 15)

In [32]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

In [34]:
df["age"].mean()

np.float64(29.69911764705882)

In [35]:
df["age"].median()

28.0

In [36]:
df["age"] = df["age"].fillna(df["age"].median())

In [37]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [42]:
df = df.dropna()

In [43]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [ ]:
placement = np.